In [2]:
import torch

In [11]:
zero = torch.zeros(4)
one = torch.ones(4)

print(zero)
print(one)

tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])


In [12]:
zero_detach = zero.detach()
one_detach = one.detach()

print(zero_detach)
print(one_detach)

tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])


In [13]:
zero[0] = 9

print(zero_detach, 'detached version')
print(zero, 'original version')

tensor([9., 0., 0., 0.]) detached version
tensor([9., 0., 0., 0.]) original version


In [7]:
b_0 = torch.rand(10)
print(b_0.size())
b_0.repeat(1, 5).size()

torch.Size([10])


torch.Size([1, 50])